$ANSIBLE_VAULT;1.1;AES256
33323865366461623834323832613934346532313437646332373561393763373436383461383535
3863643037363937383266386366316634653633633833660a633336363932323939326161623663
37366435393065393064636465656537356163383036396336316565336264313036313733373735
3563613662353637630a653634666330336132353131343462366166633362613964333861646165
61383062656133326634613537613332353765336365396230333465663735366130
