---
- name: Query all tenants
  cisco.aci.aci_tenant:
    host: '{{ ansible_host }}'
    username: '{{ ansible_user }}'
    password: '{{ ansible_password }}'

    validate_certs: false
    state: query
  register: all_tenants
